### ISSUE TITLE
set lower livestream resolution / bitrate to get more fps?

### ISSUE THREAD

**Issue by gmiwoj** [sumdog/RearViewMirror#14]
live stream resolution and quality is permanently set to max, so i get 1 frame every 5 seconds. 
any way to set lower size and bitrate values ? 

i've even searched source files, hoping to find some variables i could manually change and make my custom build. 
but i couldn't find anything. i don't know much about c#.

EDIT. never mind. i've found cam2ip.exe app works better for me

**Comment by sumdog** [comment]
Hey, sorry I didn't respond to this earlier. I haven't worked on this project in quite some time. I don't even have a license to Visual Studio any more and I think I lost a very old branch where I tried to update the project to use a modern VS. There are some other forks going around you might want to try.

The video and motion detection is done using an ancient and unmaintained library called AForge. Once upon a time I started down the path of ripping it out and replacing it with ffmpeg, but never got around to finishing that project either. I'm open to receiving patches, but I no longer have the tooling to build this project.
