### ISSUE TITLE
Sound is not playing

### ISSUE THREAD

**Issue by basstwo** [sumdog/RearViewMirror#9]
I have a sound picked.  I have it set to play on motion alert.  The image shows up when motion is detected.  But the sound doesn't play.

**Comment by sumdog** [comment]
If I recall correctly, the file has to be in wav format. Are you using a wav file (not an mp3). 

Which Windows version are you on and is there anything in the debugging logs (found in the context menu)?

**Comment by basstwo** [comment]
I took a look at the log.  The problem was that the wav file wasn't a PCM wave file.  I had just grabbed one from the Windows Alerts (Cityscape).  Thanks!
